"""empty message

Revision ID: 138b0c002974
Revises: 5fe1a705580f
Create Date: 2019-04-29 14:02:20.447331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '138b0c002974'
down_revision = '5fe1a705580f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hobby', 'hobby')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hobby', sa.Column('hobby', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
