"""empty message

Revision ID: 4cb191e27378
Revises: 824f83cea63d
Create Date: 2019-04-29 16:22:55.236221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb191e27378'
down_revision = '824f83cea63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'user_id')
    # ### end Alembic commands ###
