"""empty message

Revision ID: 824f83cea63d
Revises: cc200f5cb19f
Create Date: 2019-04-29 16:22:28.273559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '824f83cea63d'
down_revision = 'cc200f5cb19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('characters_ibfk_1', 'characters', type_='foreignkey')
    op.drop_column('characters', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('characters_ibfk_1', 'characters', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
