"""empty message

Revision ID: c0ff923eabe7
Revises: e617e4bff38d
Create Date: 2019-04-29 11:55:43.601871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0ff923eabe7'
down_revision = 'e617e4bff38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'autograph')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('autograph', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
