"""empty message

Revision ID: cc200f5cb19f
Revises: 138b0c002974
Create Date: 2019-04-29 14:02:49.894905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc200f5cb19f'
down_revision = '138b0c002974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hobby', sa.Column('hobby', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hobby', 'hobby')
    # ### end Alembic commands ###
