"""empty message

Revision ID: e617e4bff38d
Revises: e9d44bd2e0e5
Create Date: 2019-04-29 11:18:43.629756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e617e4bff38d'
down_revision = 'e9d44bd2e0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('autograph', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'autograph')
    # ### end Alembic commands ###
